language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: false
      compiler: g++-5
      env: MKPM_CXX=g++-5
           MKPM_CC=gcc-5
    - os: linux
      sudo: false
      compiler: clang-3.6
      env: MKPM_CXX=clang++-3.6
           MKPM_CC=clang-3.6
    - os: osx
      compiler: clang++
    - os: osx
      compiler: clang++
      env: MKPM_CROSS=i386
    - os: osx
      compiler: clang++
      env: MKPM_CROSS=x86_64
    - os: osx
      compiler: clang++
      env: MKPM_CROSS=armv7
    - os: osx
      compiler: clang++
      env: MKPM_CROSS=armv7s
    - os: osx
      compiler: clang++
      env: MKPM_CROSS=arm64

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-5

script:
  - ./build/travis.sh
